<<<<<<< HEAD
2021-08-20 23:58:02,980 ERROR: Exception on /explore [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
=======
2021-08-18 22:26:32,998 ERROR: Exception on /index [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
>>>>>>> a95ef38e97514b9a43eb0af98367714700e89e39
Traceback (most recent call last):
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
<<<<<<< HEAD
  File "/Users/vajo/local/job/microblog/app/routes.py", line 153, in explore
    next_url=next_url, prev_url=prev_url)
=======
  File "/Users/vajo/local/job/microblog/app/routes.py", line 25, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts.items)
>>>>>>> a95ef38e97514b9a43eb0af98367714700e89e39
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vajo/local/job/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
<<<<<<< HEAD
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}
  File "/Users/vajo/local/job/microblog/app/templates/index.html", line 21, in block 'app_content'
=======
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/vajo/local/job/microblog/app/templates/index.html", line 21, in block 'content'
>>>>>>> a95ef38e97514b9a43eb0af98367714700e89e39
    {% include '_post.html' %}
  File "/Users/vajo/local/job/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
  File "/Users/vajo/local/job/microblog/app/models.py", line 36, in avatar
    digest = md5(self.email.lower().encode('utf-8')).hexdigest()
AttributeError: 'NoneType' object has no attribute 'lower'
<<<<<<< HEAD
=======
2021-08-18 22:26:34,455 ERROR: Exception on /user/boot [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/vajo/local/job/microblog/app/routes.py", line 72, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vajo/local/job/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/vajo/local/job/microblog/app/templates/user.html", line 6, in block 'content'
    <td><img src="{{ user.avatar(128) }}"></td>
  File "/Users/vajo/local/job/microblog/app/models.py", line 36, in avatar
    digest = md5(self.email.lower().encode('utf-8')).hexdigest()
AttributeError: 'NoneType' object has no attribute 'lower'
2021-08-18 22:27:33,072 INFO: Microblog startup [in /Users/vajo/.Trash/microblog 22.27.00/app/__init__.py:44]
2021-08-18 22:27:37,494 ERROR: Exception on /index [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/vajo/.Trash/microblog 22.27.00/app/routes.py", line 25, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts.items)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vajo/.Trash/microblog 22.27.00/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/vajo/.Trash/microblog 22.27.00/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/vajo/.Trash/microblog 22.27.00/app/templates/index.html", line 21, in block 'content'
    {% include '_post.html' %}
  File "/Users/vajo/.Trash/microblog 22.27.00/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
  File "/Users/vajo/.Trash/microblog 22.27.00/app/models.py", line 36, in avatar
    digest = md5(self.email.lower().encode('utf-8')).hexdigest()
AttributeError: 'NoneType' object has no attribute 'lower'
>>>>>>> a95ef38e97514b9a43eb0af98367714700e89e39
