2021-08-18 20:58:38,775 ERROR: Exception on / [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/vajo/local/job/microblog/app/routes.py", line 23, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vajo/local/job/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/vajo/local/job/microblog/app/templates/index.html", line 21, in block 'content'
    {% include '_post.html' %}
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vajo/local/job/microblog/app/templates/_post.html", line 6, in template
    <a href="{{ url_for('user'), username=post.author.username }}">
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='
2021-08-18 21:00:23,840 INFO: Microblog startup [in /Users/vajo/local/job/microblog/app/__init__.py:44]
2021-08-18 21:03:18,856 INFO: Microblog startup [in /Users/vajo/local/job/microblog/app/__init__.py:44]
2021-08-18 21:28:12,505 INFO: Microblog startup [in /Users/vajo/local/job/microblog/app/__init__.py:44]
2021-08-18 22:35:34,810 INFO: Microblog startup [in /Users/vajo/local/job/microblog/app/__init__.py:44]
2021-08-18 22:35:38,569 ERROR: Exception on /user/boot [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/vajo/local/job/microblog/app/routes.py", line 72, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vajo/local/job/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/vajo/local/job/microblog/app/templates/user.html", line 6, in block 'content'
    <td><img src="{{ user.avatar(128) }}"></td>
  File "/Users/vajo/local/job/microblog/app/models.py", line 36, in avatar
    digest = md5(self.email.lower().encode('utf-8')).hexdigest()
AttributeError: 'NoneType' object has no attribute 'lower'
2021-08-18 22:35:41,917 ERROR: Exception on /user/boot [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/vajo/local/job/microblog/app/routes.py", line 72, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vajo/local/job/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/vajo/local/job/microblog/app/templates/user.html", line 6, in block 'content'
    <td><img src="{{ user.avatar(128) }}"></td>
  File "/Users/vajo/local/job/microblog/app/models.py", line 36, in avatar
    digest = md5(self.email.lower().encode('utf-8')).hexdigest()
AttributeError: 'NoneType' object has no attribute 'lower'
2021-08-18 22:35:46,397 ERROR: Exception on /user/boot [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/vajo/local/job/microblog/app/routes.py", line 72, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vajo/local/job/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/vajo/local/job/microblog/app/templates/user.html", line 6, in block 'content'
    <td><img src="{{ user.avatar(128) }}"></td>
  File "/Users/vajo/local/job/microblog/app/models.py", line 36, in avatar
    digest = md5(self.email.lower().encode('utf-8')).hexdigest()
AttributeError: 'NoneType' object has no attribute 'lower'
