<<<<<<< HEAD
2021-08-18 22:37:22,746 ERROR: Exception on /index [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
=======
2021-08-10 23:47:07,556 ERROR: Exception on /user/yuri [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
>>>>>>> a95ef38e97514b9a43eb0af98367714700e89e39
Traceback (most recent call last):
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
<<<<<<< HEAD
  File "/Users/vajo/local/job/microblog/app/routes.py", line 25, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts.items)
=======
  File "/Users/vajo/local/job/microblog/app/routes.py", line 66, in user
    return render_template('user.html', user=user, posts=posts)
>>>>>>> a95ef38e97514b9a43eb0af98367714700e89e39
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
<<<<<<< HEAD
  File "/Users/vajo/local/job/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/vajo/local/job/microblog/app/templates/index.html", line 21, in block 'content'
    {% include '_post.html' %}
  File "/Users/vajo/local/job/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
  File "/Users/vajo/local/job/microblog/app/models.py", line 36, in avatar
    digest = md5(self.email.lower().encode('utf-8')).hexdigest()
AttributeError: 'NoneType' object has no attribute 'lower'
2021-08-18 22:37:23,607 ERROR: Exception on /index [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/vajo/local/job/microblog/app/routes.py", line 25, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts.items)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vajo/local/job/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/vajo/local/job/microblog/app/templates/index.html", line 21, in block 'content'
    {% include '_post.html' %}
  File "/Users/vajo/local/job/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
  File "/Users/vajo/local/job/microblog/app/models.py", line 36, in avatar
    digest = md5(self.email.lower().encode('utf-8')).hexdigest()
AttributeError: 'NoneType' object has no attribute 'lower'
2021-08-18 22:37:24,554 ERROR: Exception on /user/boot [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
=======
  File "/Users/vajo/local/job/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 33, in top-level template code
    {% block content %}
  File "/Users/vajo/local/job/microblog/app/templates/user.html", line 16, in block 'content'
    <form action="{{ url_for('follow', username=user.username) }}" method="post">
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'follow' with values ['username']. Did you mean 'login' instead?
2021-08-10 23:48:23,039 ERROR: Exception on /user/yuri [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
>>>>>>> a95ef38e97514b9a43eb0af98367714700e89e39
Traceback (most recent call last):
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
<<<<<<< HEAD
  File "/Users/vajo/local/job/microblog/app/routes.py", line 72, in user
    return render_template('user.html', user=user, posts=posts, form=form)
=======
  File "/Users/vajo/local/job/microblog/app/routes.py", line 66, in user
    return render_template('user.html', user=user, posts=posts)
>>>>>>> a95ef38e97514b9a43eb0af98367714700e89e39
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/vajo/local/job/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
<<<<<<< HEAD
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/vajo/local/job/microblog/app/templates/user.html", line 6, in block 'content'
    <td><img src="{{ user.avatar(128) }}"></td>
  File "/Users/vajo/local/job/microblog/app/models.py", line 36, in avatar
    digest = md5(self.email.lower().encode('utf-8')).hexdigest()
AttributeError: 'NoneType' object has no attribute 'lower'
2021-08-18 22:37:25,315 ERROR: Exception on /index [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
=======
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 33, in top-level template code
    {% block content %}
  File "/Users/vajo/local/job/microblog/app/templates/user.html", line 16, in block 'content'
    <form action="{{ url_for('follow', username=user.username) }}" method="post">
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'follow' with values ['username']. Did you mean 'login' instead?
2021-08-10 23:48:25,748 ERROR: Exception on /user/alex [GET] [in /Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py:1455]
>>>>>>> a95ef38e97514b9a43eb0af98367714700e89e39
Traceback (most recent call last):
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
<<<<<<< HEAD
  File "/Users/vajo/local/job/microblog/app/routes.py", line 25, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts.items)
=======
  File "/Users/vajo/local/job/microblog/app/routes.py", line 66, in user
    return render_template('user.html', user=user, posts=posts)
>>>>>>> a95ef38e97514b9a43eb0af98367714700e89e39
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
<<<<<<< HEAD
  File "/Users/vajo/local/job/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/vajo/local/job/microblog/app/templates/index.html", line 21, in block 'content'
    {% include '_post.html' %}
  File "/Users/vajo/local/job/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
  File "/Users/vajo/local/job/microblog/app/models.py", line 36, in avatar
    digest = md5(self.email.lower().encode('utf-8')).hexdigest()
AttributeError: 'NoneType' object has no attribute 'lower'
=======
  File "/Users/vajo/local/job/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/vajo/local/job/microblog/app/templates/base.html", line 33, in top-level template code
    {% block content %}
  File "/Users/vajo/local/job/microblog/app/templates/user.html", line 16, in block 'content'
    <form action="{{ url_for('follow', username=user.username) }}" method="post">
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/vajo/local/job/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'follow' with values ['username']. Did you mean 'login' instead?
2021-08-10 23:49:39,944 INFO: Microblog startup [in /Users/vajo/local/job/microblog/app/__init__.py:44]
2021-08-11 00:01:56,415 INFO: Microblog startup [in /Users/vajo/local/job/microblog/app/__init__.py:44]
2021-08-11 00:02:11,194 INFO: Microblog startup [in /Users/vajo/local/job/microblog/app/__init__.py:44]
2021-08-15 21:40:56,986 INFO: Microblog startup [in /Users/vajo/local/job/microblog/app/__init__.py:44]
2021-08-15 22:35:28,951 INFO: Microblog startup [in /Users/vajo/local/job/microblog/app/__init__.py:44]
2021-08-15 22:50:25,707 INFO: Microblog startup [in /Users/vajo/local/job/microblog/app/__init__.py:44]
2021-08-18 20:20:56,609 INFO: Microblog startup [in /Users/vajo/local/job/microblog/app/__init__.py:44]
2021-08-18 20:58:26,791 INFO: Microblog startup [in /Users/vajo/local/job/microblog/app/__init__.py:44]
>>>>>>> a95ef38e97514b9a43eb0af98367714700e89e39
